#include "backend/nir/NarvalDialect.h"
#include "backend/nir/NarvalOps.h"
#include "backend/nir/NarvalTypes.h"

#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/TypeSwitch.h"

// Pull in the generated dialect implementation (ctor, dtor, TypeID).
#include "NarvalDialect.cpp.inc"

using namespace mlir;
using namespace mlir::narval;

void NarvalDialect::initialize() {
    addOperations<
#define GET_OP_LIST
#include "NarvalOps.cpp.inc"
    >();

    addTypes<
#define GET_TYPEDEF_LIST
#include "NarvalTypes.cpp.inc"
    >();
}

//  Attribute printer / parser 
// The Narval dialect has no custom attributes; these are required because the
// generated header declares them as virtual overrides.

mlir::Attribute NarvalDialect::parseAttribute(mlir::DialectAsmParser& parser,
                                               mlir::Type type) const {
    parser.emitError(parser.getNameLoc(),
                     "narval dialect has no custom attributes");
    return {};
}

void NarvalDialect::printAttribute(mlir::Attribute attr,
                                    mlir::DialectAsmPrinter& printer) const {
    printer << "<unknown narval attribute>";
}

// parseType / printType are generated by NarvalTypes.cpp.inc (included below).
// They provide mnemonic-based dispatch for !narval.value, !narval.ref, etc.
#define GET_TYPEDEF_CLASSES
#include "NarvalTypes.cpp.inc"
