#include "backend/nir/NarvalDialect.h"
#include "backend/nir/NarvalOps.h"
#include "backend/nir/NarvalTypes.h"
#include "backend/nir/NarvalAttrs.h"

#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/TypeSwitch.h"

// Pull in the generated dialect implementation (ctor, dtor, TypeID).
#include "NarvalDialect.cpp.inc"

using namespace mlir;
using namespace mlir::narval;

void NarvalDialect::initialize() {
    addOperations<
#define GET_OP_LIST
#include "NarvalOps.cpp.inc"
    >();

    addTypes<
#define GET_TYPEDEF_LIST
#include "NarvalTypes.cpp.inc"
    >();

    addAttributes<
#define GET_ATTRDEF_LIST
#include "NarvalAttrs.cpp.inc"
    >();
}

// parseType / printType implementations generated from NarvalTypes.td.
#define GET_TYPEDEF_CLASSES
#include "NarvalTypes.cpp.inc"

// Attr class implementations + dialect parseAttribute/printAttribute dispatch
// are all generated by GET_ATTRDEF_CLASSES.
#define GET_ATTRDEF_CLASSES
#include "NarvalAttrs.cpp.inc"

// OptimizeAttr — custom parse/print (hasCustomAssemblyFormat = 1).
// This attribute is only ever created programmatically from @optimize hints;
// it is never parsed from textual MLIR. Provide minimal stubs.
mlir::Attribute OptimizeAttr::parse(::mlir::AsmParser& /*parser*/,
                                     ::mlir::Type /*type*/) {
    return {};
}
void OptimizeAttr::print(::mlir::AsmPrinter& p) const {
    p << "optimize";
}
