// LowerLinalgVectorizationPass.cpp — Fase 5: linalg vectorization + full vector lowering.

#include "backend/nir/NarvalPasses.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Transforms/LoweringPatterns.h"
#include "mlir/Dialect/Vector/Transforms/VectorTransforms.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"

using namespace mlir;
using namespace mlir::vector;

namespace nv {
namespace {

//===----------------------------------------------------------------------===//
// NarvalLinalgVectorizePass
//===----------------------------------------------------------------------===//

struct NarvalLinalgVectorizePass
    : public PassWrapper<NarvalLinalgVectorizePass, OperationPass<ModuleOp>> {

    MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(NarvalLinalgVectorizePass)

    StringRef getName() const override { return "narval-linalg-vectorize"; }

    void getDependentDialects(DialectRegistry& registry) const override {
        registry.insert<vector::VectorDialect>();
    }

    void runOnOperation() override {
        ModuleOp module = getOperation();
        IRRewriter rewriter(&getContext());

        for (auto func : module.getOps<func::FuncOp>()) {
            if (func.isExternal() || func.getBody().empty()) continue;
            SmallVector<linalg::LinalgOp> to_vectorize;
            Block& entry = func.getBody().front();
            for (Operation& op : entry.getOperations()) {
                if (auto lop = dyn_cast<linalg::LinalgOp>(&op))
                    to_vectorize.push_back(lop);
            }
            for (linalg::LinalgOp lop : to_vectorize) {
                rewriter.setInsertionPoint(lop);
                // Collect static sizes from the loop bounds (parallel dims only).
                // For linalg.matmul, the vectorization sizes must be the output
                // shape [M, N] — the K reduction dim is handled internally.
                SmallVector<int64_t> vecSizes;
                for (auto [idx, iterType] :
                     llvm::enumerate(lop.getIteratorTypesArray())) {
                    if (iterType == utils::IteratorType::parallel) {
                        auto range = lop.getStaticLoopRanges();
                        if (!range.empty() && idx < range.size() &&
                            range[idx] != ShapedType::kDynamic)
                            vecSizes.push_back(range[idx]);
                    }
                }
                // Only vectorize if we have fully static parallel dims.
                if (!vecSizes.empty()) {
                    (void)linalg::vectorize(rewriter, lop.getOperation(),
                                            vecSizes, {});
                }
            }
        }
    }
};

//===----------------------------------------------------------------------===//
// NarvalVectorLoweringPass
//===----------------------------------------------------------------------===//
// Lowers the vector ops generated by NarvalLinalgVectorizePass:
//   vector.contract → outerproduct → multi_reduction → reduction
// Uses applyPartialConversion so unhandled ops stay legal.

struct NarvalVectorLoweringPass
    : public PassWrapper<NarvalVectorLoweringPass, OperationPass<ModuleOp>> {

    MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(NarvalVectorLoweringPass)

    StringRef getName() const override { return "narval-vector-lowering"; }

    void getDependentDialects(DialectRegistry& registry) const override {
        registry.insert<vector::VectorDialect, arith::ArithDialect>();
    }

    void runOnOperation() override {
        ModuleOp module = getOperation();
        MLIRContext* ctx = &getContext();

        ConversionTarget target(*ctx);
        target.addLegalDialect<func::FuncDialect,
                               arith::ArithDialect,
                               memref::MemRefDialect,
                               scf::SCFDialect,
                               LLVM::LLVMDialect,
                               vector::VectorDialect>();
        // Only these vector ops must be lowered — the rest stay legal.
        target.addIllegalOp<vector::ContractionOp,
                            vector::MultiDimReductionOp,
                            vector::OuterProductOp>();
        target.markUnknownOpDynamicallyLegal([](Operation*) { return true; });

        RewritePatternSet patterns(ctx);

        // vector.contract → dot-product style (Dot strategy).
        // Safer than LLVMIntr (which assumes column-major layout) for our
        // row-major memref tensors.
        populateVectorContractLoweringPatterns(
            patterns,
            VectorContractLowering::Dot);

        // vector.multi_reduction → vector.reduction (InnerReduction strategy)
        // Needed for any remaining multi_reduction ops.
        populateVectorMultiReductionLoweringPatterns(
            patterns,
            VectorMultiReductionLowering::InnerReduction);

        // vector.broadcast → extract + insert sequences
        populateVectorBroadcastLoweringPatterns(patterns);

        if (failed(applyPartialConversion(module, target, std::move(patterns)))) {
            // Non-fatal: remaining ops will be handled by later passes or fallback.
            module.emitWarning("narval-vector-lowering: some vector ops not lowered");
        }
    }
};

} // namespace

std::unique_ptr<mlir::Pass> createNarvalLinalgVectorizePass() {
    return std::make_unique<NarvalLinalgVectorizePass>();
}

std::unique_ptr<mlir::Pass> createNarvalVectorLoweringPass() {
    return std::make_unique<NarvalVectorLoweringPass>();
}

} // namespace nv
