// NarvalVectorLoweringPass.cpp — Fase 5: full vector lowering.
// Lowers the vector ops generated by NarvalLinalgVectorizePass:
//   vector.contract → outerproduct → multi_reduction → reduction
// Uses applyPartialConversion so unhandled ops stay legal.

#include "backend/nir/NarvalPasses.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Transforms/LoweringPatterns.h"
#include "mlir/Dialect/Vector/Transforms/VectorTransforms.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"

#define GEN_PASS_DEF_NARVALVECTORLOWERINGPASS
#include "NarvalPasses.h.inc"

using namespace mlir;
using namespace mlir::vector;

namespace nv {
namespace {

//===----------------------------------------------------------------------===//
// NarvalVectorLoweringPass
//===----------------------------------------------------------------------===//

struct NarvalVectorLoweringPass
    : public ::impl::NarvalVectorLoweringPassBase<NarvalVectorLoweringPass> {

    void runOnOperation() override {
        ModuleOp module = getOperation();
        MLIRContext* ctx = &getContext();

        ConversionTarget target(*ctx);
        target.addLegalDialect<func::FuncDialect,
                               arith::ArithDialect,
                               memref::MemRefDialect,
                               scf::SCFDialect,
                               LLVM::LLVMDialect,
                               vector::VectorDialect>();
        // Only these vector ops must be lowered — the rest stay legal.
        target.addIllegalOp<vector::ContractionOp,
                            vector::MultiDimReductionOp,
                            vector::OuterProductOp>();
        target.markUnknownOpDynamicallyLegal([](Operation*) { return true; });

        RewritePatternSet patterns(ctx);

        // vector.contract → dot-product style (Dot strategy).
        // Safer than LLVMIntr (which assumes column-major layout) for our
        // row-major memref tensors.
        populateVectorContractLoweringPatterns(
            patterns,
            VectorContractLowering::Dot);

        // vector.multi_reduction → vector.reduction (InnerReduction strategy)
        // Needed for any remaining multi_reduction ops.
        populateVectorMultiReductionLoweringPatterns(
            patterns,
            VectorMultiReductionLowering::InnerReduction);

        // vector.broadcast → extract + insert sequences
        populateVectorBroadcastLoweringPatterns(patterns);

        if (failed(applyPartialConversion(module, target, std::move(patterns)))) {
            // Non-fatal: remaining ops will be handled by later passes or fallback.
            module.emitWarning("narval-vector-lowering: some vector ops not lowered");
        }
    }
};

} // namespace

std::unique_ptr<mlir::Pass> createNarvalVectorLoweringPass() {
    return std::make_unique<NarvalVectorLoweringPass>();
}

} // namespace nv
